// Codegen: read the Untitled UI line SVGs in ./svg and emit icons.gen.ts —
// a name → inner-markup map. The root <svg> attributes (24×24 viewBox,
// currentColor stroke, width 2, round caps) are uniform across the line set and
// are applied by the Icon component, so only the inner paths are stored.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const svgDir = join(here, 'svg')

const files = readdirSync(svgDir).filter((f) => f.endsWith('.svg'))
const entries = files
  .map((f) => f.replace(/\.svg$/, ''))
  .sort()
  .map((name) => {
    const raw = readFileSync(join(svgDir, `${name}.svg`), 'utf8')
    const inner = raw
      .replace(/[\s\S]*?<svg[^>]*>/, '')
      .replace(/<\/svg>\s*$/, '')
      .replace(/\s+/g, ' ')
      .trim()
    return `  '${name}': '${inner.replace(/'/g, "\\'")}',`
  })

const out = `// AUTO-GENERATED by gen-icons.mjs — do not edit by hand.
// Untitled UI Icons (Line, v1.6). Inner markup only; the <svg> wrapper attributes
// are applied by the Icon component.

export const ICON_BODIES = {
${entries.join('\n')}
} as const

export type IconName = keyof typeof ICON_BODIES
`
writeFileSync(join(here, 'icons.gen.ts'), out)
console.log(`generated icons.gen.ts with ${entries.length} icons`)
